version: '3.7'

services:

  api:
    container_name: solarlab-academy-api
    build:
      context: .
      dockerfile: src/Board/Host/Board.Host.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings__PostgresDb=Server=postgres;Database=postgres;Username=postgres;Password=password;Port=5432
    depends_on:
      - "postgres"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  pg-data: