version: '3.7'

services:

  api:
    container_name: solarlab-academy-api
    build:
      context: .
      dockerfile: src/Board/Host/Board.Host.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings__PostgresBoardDb=Server=postgres;Database=Board;Username=postgres;Password=password;Port=5432
    networks:
      - solarlab-academy-network
    depends_on:
      - "migrator"

  migrator:
    container_name: solarlab-academy-migrator
    build:
      context: .
      dockerfile: src/Board/Host/Board.Host.DbMigrator/Dockerfile
    environment:
      - ConnectionStrings__PostgresBoardDb=Server=postgres;Database=Board;Username=postgres;Password=password;Port=5432
    networks:
      - solarlab-academy-network
    depends_on:
      - "postgres"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "postgres"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: "Board"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - solarlab-academy-network
  
volumes:
  pg-data:
  
networks:
  solarlab-academy-network: